language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt coverage test coverageReport
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.11.12"'
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SONA_USER=snowplow
