language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt coverage test coverageReport
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.11.12"'
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SONA_USER=snowplow
  - secure: jvz1AGHlE0llbJ0xxkKqNrGIEkfXfnex4ulbSawI3L4Ch2HDRyjRP6tXkg8CFaK0Luu/vCd4Qws7dQTOG9pj2sQbrj51wki51ueiHGFRYjrNe/ge2W+BGOscPgz7XQ/RpkOGEMxpMjSXXUFdAlb3xCD/wl+t3b5zfAxZ8v3xq6jkVcdzK2q/mjWIFG+IaAhHMuYg0xT7aKReguMy8Fhcl+H77jSZm/pML1rnRJivu+pHxgxaJV2oW5IFVM/iQrQpihjI7VBgcvfyRAXpM3OE6/K5kLZtXTd50ZXZb1MgEOP1970NqNt7s03FEdKpj+t3mkPxGpxeqnp5Dv/rEAA2GQZ9gszTZbsgFxaJdKSoM2gDqp5G42qSvdQHp6FRDMst2OCMDS4UYIn6B1v50WgKlvcH0xfJhcsa8EK99jHLKvVGKETKuph6RMNeTRj0HOMrDFzjbd7rqRZNB3PkBSUjTm6VeO7cvNQMJuqxULU0mDVpkeTsL4RxtKmBvrStww9EPyFiKBAJR4vux9Sm+uDiHgxcN3EkFQ3hVq/miFZklFuYJuugxUVC4GiC+mTqZfHcIkVpuBhb+MgQJJ7RYeunFX2pFzui7gCV7It9B/gEy33A4i/Wt5CMit0t7HNHHkYFZ2fOjhxwFMUF0gklRus2ytkuZNEo1q0whWvUUqW+JBY=
  - secure: ZSiRtBfe5Mql2XWSINr6co7c9T1hA3bmmAnPAgMcO+J3EpdKGGh54yFB8CwmV7RVlHmxk6zLTYcwEVUzur/EtZ4YCdIk/xwpFFNWKMWQBGGtCUH6SW62h1eierfJidT7bOWFpTk9nygq5lr4i2tEPUMCr/DRo8+gaFdF53kzQWWL6vjdZ7uYTi/MPJvIyNCQduSwqGUg4nHwmz98v0fTybYa2qju5ciUs/0nzFTduR6wAD9+VWP/UHimbr8qGx4GVh2GlM9Jo/GhpjX6RlZGbX31SLhGhbeJyMK82LcI6YmEzvuFR4MN5lH24OtdT3UOdZYwqK9Gmq3IoqjhLH+C4N4GCtcoGGsKFbAsDCKKoEW4CT2AjVNi2NOWTBCznIenItFoQ807xowpKFzJ7h/oPs5Gn0oTWzdw7dQXCwSjeE+qAOBnARWAT7IGJqRGPH4Xuz9Xx2nwEnP0QMuGLdOYJTu5V/Vr4jcDA/xlwQAYlx4tnatz1kbAjTb7UH79pv6HHIpAoMDQTMBnUjyXdpw2gUXWzz8C4BqnMjTVoQFZZDKq2vaI68we06G13tXP7J5mwN+UeEFEYJ3u0cNnNBC5N3Am5H1D1C5xQ7O5dvFQtWhfD+sf789dVNZh8+3SRO1yFSaXMqXycJH6D1P9tIqaR9PXwNgRnRIvdyOpgTrQ75M=
